### ISSUE TITLE
Is this a terminal thing?

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#117]
organizing some books i downloaded, seems to happen a lot
using foot terminal

the m 95 works
its just that after the 5 things get warped
so its a visual problem

https://user-images.githubusercontent.com/98880063/164073866-97e52805-b473-48ac-8ac0-98d03f63c720.mp4

**Comment by leo-arch** [comment]
No, this isn't terminal related, it's an actual clifm bug. I'll let you know when it's fixed.

**Comment by DNDEBUG** [comment]
alright

**Comment by leo-arch** [comment]
I think I know where the problem comes from. Your terminal was taking the whole screen until you opened the file, which produced the screen to be automatically split into two: my guess is that clifm isn't aware of that change and is making the calculations based on the old values.

So, try the same thing but without opening the file, and, conversely, the same thing after closing the file (returning to the previous terminal size). If I'm right, the issue shouldn't come up. In this case, I only need to retrieve terminal dimensions immediately before doing the calculation for the current suggestion (though I'm not sure that is the best approach).

**Comment by leo-arch** [comment]
The issue should be solved now @DNDEBUG.

**Comment by DNDEBUG** [comment]
I Imagined that it was caused by the window changing size
no idea how it can be recalculated

**Comment by leo-arch** [comment]
You just wait for a signal (SIGWINCH) via `signal(3)` that informs you about window resizes. Once you got that signal, get the new dimensions using `ioctl(3)`.

So, if the problem was solved, please close this issue.
