### ISSUE TITLE
Log from outside files interferes on stuff

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#118]
damn bro, caught in 1366x768p 📷

https://user-images.githubusercontent.com/98880063/164325010-49d9040e-73d4-4d87-a72e-465679bfdb5b.mp4

https://user-images.githubusercontent.com/98880063/164325015-3afc4d8c-6e17-4ef6-bee4-b6f432f3df20.mp4

this even caused clifm to hang
i coundnt do anything and had to close the window

**Comment by leo-arch** [comment]
The issue here is that `mpv` is printing to both STDERR and STDOUT.

Until now, backgrounding an application automatically muted STDOUT, but not STDERR, and there was no way to do this. In the last commit I fixed this. So, install the latest version and follow these steps:

To silence both, at least when auto-opening the file (via _Lira_), edit the mimelist file (`mm edit`) as follows:

```
X:^video/.*=mpv %f !EO &
```
`%f` is a placeholder for the file to be opened
`!EO` instructs CliFM to silence both STDERR and STDOUT
`&` is to run the command in the background

In a regular shell, this amount to: `mpv FILE >/dev/null 2>&1 &`

Consult the [documentation](https://github.com/leo-arch/clifm/wiki/Specifics#resource-opener) for further details.

**Comment by DNDEBUG** [comment]
do it for every software thats does the same?

**Comment by leo-arch** [comment]
I don't understand you question? What do you mean exactly?

**Comment by DNDEBUG** [comment]
first video: llpp
second video: mpv
also why it doesn't happen when i run it without &?

**Comment by leo-arch** [comment]
When you open a file directly specifying the opening application (`APP FILE`), CliFM will execute exactly what you told, nothing more. The new addition to _Lira_ applies to files opened automatically (`FILE` / `ELN`), that is, without specifying the opening application (in which case CliFM will search for an available applicatione in the mimelist file).

**Comment by DNDEBUG** [comment]
ok but i did open it with just ELN
the thing only happens when ELN&

**Comment by leo-arch** [comment]
What's exactly the `video` line in you mimelist file?

**Comment by leo-arch** [comment]
If you want to always open video files using `mpv`, silencing both STDERR and STDOUT, and in the background, you should add this:

```
^video/.*=mpv %f !EO &
```

If you skip the `&`here, you need to specify it in the command line.

**Comment by DNDEBUG** [comment]
so i need to do ot for llpp too?

**Comment by leo-arch** [comment]
That's it. The thing is that _Lira_ will use the first available application in the mimelist file. So, if you place `mpv` before `llpp`, and `mpv` exists, this will be used to open the file. To open the file with a different application, you either specify it directly in the command line (`APP FILE`) or you can use the `ow` command, which stands for `open with`.

**Comment by DNDEBUG** [comment]
no, i have llpp for pdf and mpv for video and audio

**Comment by leo-arch** [comment]
Ok. in that case, if `llpp` behaves like `mpv`, yes, you should do the same thing for `llpp` too.

**Comment by leo-arch** [comment]
```
X:.*/pdf$=llpp %f !EO &
X:video/.*=mpv %f !EO %
```

**Comment by DNDEBUG** [comment]
it's weird how running a file like
1 it works well
but 1& it happens
i tough using & detaches de process from the terminal
so why is it getting stderr and stdout stuff?
can't this be prevented from interfering on clifm?

**Comment by leo-arch** [comment]
Are you using the latest version of CliFM? I do not experience such behavior. `ELN` and `ELN&` do the same thing if the mime definition is like the one described above.

**Comment by DNDEBUG** [comment]
haven't set like it yet
but why does it happen?
shouldn't & detach the process?

**Comment by leo-arch** [comment]
>  tough using & detaches de process from the terminal

This is not exactly true. `&` just runs the program in the background, not detached. If you run, in any regular shell, `mpv FILE &` you still see mpv printing to STDOUT in your current terminal.

**Comment by DNDEBUG** [comment]
ok i guess
but it should be looked into
this stderr causes the same visual problem as the last bug i reported
#117

**Comment by leo-arch** [comment]
The videos you sent before were quite clear and informative. Maybe a video about this latter issue could be useful too.

**Comment by DNDEBUG** [comment]
this stder thing even caused clifm to hang
i had to close the terminal and run it again
unfortunately i wasn't recording when it happened

**Comment by leo-arch** [comment]
I just need to reproduce the thing to be able to fix it. As for me, the new features work as expected.

**Comment by DNDEBUG** [comment]
it's late, i need to sleep
I'll seek more evidences tomorrow

**Comment by leo-arch** [comment]
No problem. I'll wait for them: I'm the first person in this world interested in fixing CliFM's issues.

**Comment by leo-arch** [comment]
I've been playing around with tiling window managers (i3 and xmonad): never really used any of them, which is why CliFM was mainly developed having stacking WM's in sight. I just thought a tiling window manager might give rise to some unknown issue (at least for me of course). And it does. The constant window resizing does not play well with CliFM's interface: ideally, the list of files should be updated upon resize, but it doesn't.

I also thought that the tiling nature of these window managers could be the source of the current issue, just to find out that some programs, like `feh` (no matter what WM you're using, tiling or stacking), have issues when automatically run in the background (`ELN&`): CliFM's prompt might become unresponsive for a few seconds. Feh is the only program I aware of exhibiting this behavior, but I'm sure it's not the only one.

This led me to think that maybe your issue is rooted in the specific programs you're using to automatically open files (`llpp` and `mpv` work fine though).

**Comment by DNDEBUG** [comment]
hmm i already forgot what this was about

**Comment by leo-arch** [comment]
@DNDEBUG, should we close this issue?

**Comment by DNDEBUG** [comment]
yeah, if this returns as a problem i'll open it again
