### ISSUE TITLE
tranlation questions

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#121]
```
#: file_operations.c:809 
msgid "bulk: Line mismatch in rename file\n"
msgstr "" 

´´´
  
is this correct or should it be "Line mismatch in renaming file"?

**Comment by leo-arch** [comment]
Hi @DNDEBUG. Yes, you're right. Fixed.

Btw, you're using a quite outdated .po file. Updated with the last commit.

Hope this won't be a major inconvenient.

**NOTE**: We were using [Hosted Weblate](https://hosted.weblate.org/projects/clifm/clifm) as translation platform, but it seems to be currently broken due to the necent update.

**Comment by DNDEBUG** [comment]
:skull: you waited for me to translate 12 billion lines before telling me that?

**Comment by leo-arch** [comment]
I'm really sorry about that, really. The whole translation thing is a mess: not being a priority, translation files remained outdated for the last releases. Working on it right now.

Btw, I guess there should be a way to merge old and new files without the need to redo everything done up to this point.
