### ISSUE TITLE
Warning that might be looked into

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#127]
```
Detected operating system: Linux
cc -o clifm src/*.c -O3 -fstack-protector-strong -march=native -Wall -DCLIFM_DATADIR=/usr/local/share  -lreadline -lacl -lcap -lmagic
src/suggestions.c: In function ‘count_words’:
src/suggestions.c:1242:70: warning: the comparison will always evaluate as ‘true’ for the pointer operand in ‘b + 1’ must not be NULL [-Waddress]
 1242 | t_word_start = (int)w + (b + 1 ? 1 : 0);
      |                                ^

**Comment by leo-arch** [comment]
Thanks! Yes, I saw that warning already. It was detected by GCC 12 (though not before).

The thing is that valgrind refuses to work with the new gcc, so that I stick to gcc 11.2 for the time being. I hope the next valgrind update will address this issue.

Though seemingly not a important defect (just an informational warning), I  need to closely look at the code and make sure the fix won't bring unexpected issues. Indeed, the fix is already there, but still commented out.

**Comment by leo-arch** [comment]
The warning should be gone now (1cc766f).

**Comment by DNDEBUG** [comment]
i compiled with clang and got no warnings

**Comment by leo-arch** [comment]
The warning was triggered by GCC 12, but not by clang (at least not up 13.0). However, it's already silenced. Closing.
