### ISSUE TITLE
Compression script

### ISSUE THREAD

**Issue by DNDEBUG** [leo-arch/CliFM#130]
make a script to compress and list files in compressed archives
7z can do most of it
and other tools to do specific stuff
like instead of using 7z use tar + some other compression
and other specific stuff like zpaq that 7z can't deal with

like this
select 1 2 3
compress sel
files 1,2,3 will be compressed with 7z, you can change the archiver.
(1) Continue (2) Change (3) Cancel
     (1) files will be compressed with these settings "-t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on"
          (1) Continue (2) Change (3) Cancel
               (1) continues normally, (2) the user can change the switches, (3) Cancel everything 
(2) The user can change the archiver to tar, zip, zpaq or any other
(3) Cancel everything

**Comment by leo-arch** [comment]
> Make a script to compress and list files in compressed archives

We already have a built-in function to handle archives via the `ac` and `ad` commands. See the [archiving](https://github.com/leo-arch/clifm/wiki/Advanced#archives) section for more info.

Maybe a plugin could be written to handle extra archive/compression types.

**Comment by DNDEBUG** [comment]
i'll take a look into helping 
but i can only organize stuff
you deal with the programming part if you want

**Comment by leo-arch** [comment]
Hi @DNDEBUG. Were the `ac`/`ad` commands useful? Do you believe we still need an extra plugin? And what cases should this plugin handle (most common cases are handled by `ac-ad`)?

**Comment by DNDEBUG** [comment]
these are only for tar kinda
7z extract most things
i'm still thinking

**Comment by DNDEBUG** [comment]
or maybe it is perfect the way it is
i should try more

**Comment by leo-arch** [comment]
Great! Just let me know.

Please reopen this issue if you think the built-in commands are somehow not enough.

**Comment by Blackbeing** [comment]
Using arguments with `ac` command. Is this possible?
`ac -rm sel` #move files recursively to archive similar to `zip -rm`

**Comment by leo-arch** [comment]
Hi @Blackbeing. No, the  `ac` command takes no parameter. Running `ac FILE...` calls **atool**(1) with the `-a` parameter, which takes care of invoking the appropriate application based on the file names and file types passed as parameters. Indeed, `ac FILE...`, provided you specify a .zip file name when asked (say, `archive.zip`), is the same as `zip -r FILE...`.

However, the `-m` parameter cannot be used with `atool`, since it just doesn't provide this option. You have two alternatives here:

1. [Create an alias](https://github.com/leo-arch/clifm/wiki/Customization#aliases) with the application/parameters you want. Ex:
```sh
alias zipm='zip -rm'
```
and then use `zipm` instead of `ac`.

2. Try creating a configuration file for `atool` (though I'm not sure the exact thing you want to accomplish here can be done this way). Consult the `atool` documentation.
3. As a last resource (far from ideal though), just run the command you want: `zip -rm FILE...`

**Comment by Blackbeing** [comment]
> [create an alias](https://github.com/leo-arch/clifm/wiki/Customization#aliases)
> with the application/parameters you want. Ex:
> ```sh
> alias zipm='zip -rm'
> ```
> and then use `zipm` instead of `ac`.

Thanks, I think I'll go with the above.
