### ISSUE TITLE
In long file listing, optionally show real size in bytes instead of based on blocks

### ISSUE THREAD

**Issue by knodalyte** [leo-arch/CliFM#131]
**Is your feature request related to a problem? Please describe.**
Showing the length of a zero length file as 4K is not helpful, and it makes sorting by size less helpful

**Describe the solution you'd like**
Support an option to display actual file size like pretty much every other file manager.

**Comment by leo-arch** [comment]
Hi @knodalyte. When it comes to file sizes (both directories and regular files), CliFM offers several options:

1. Use the `fz` command (it takes two possible parameters, `on` and `off`) to toggle full directories size (in long view mode) in -place. The `--full-dir-size` command line switch is also available.
2. Toggle the disk-usage-analyzer mode via <kbd>Alt-TAB</kbd> (or the `-t` command line switch). Full dir size is enabled by default in this mode.
3. Print files apparent sizes, instead of actual device usage (default), using the `--apparent-size` switch.
4. Use the `--si` switch to use powers of 1000 instead of 1024 for file sizes.

Hope this helps.

**Comment by knodalyte** [comment]
Thank you, I had missed the apparent-size option. That solves my issue.

Any chance that could be a config file setting?

**Comment by leo-arch** [comment]
Maybe for the next release. I'll add it to my TODO list.

Glad to be useful. Please close this issue if you think it was solved.

**Comment by leo-arch** [comment]
> Any chance that could be a config file setting?

Done! `ApparentSize` (defaults to `false`) is a new option in the configuration file.

**Comment by knodalyte** [comment]
Wow!  Thank you! 

Beyond that, thanks for clifm, it scratches an itch that I didn't know I had. Longtime Ranger user, but clifm is both leaner and meaner and more flexible.

I especially appreciate the documentation. It is extensive as well as readable. I am of an age where it takes a while for shortcuts and commands to sink in, so I find myself printing some of the tables to use as cheatsheets (commands, shortcuts, plugins).

What is surprising is the apparent lack of reviews, tutorials (maybe redundant), videos, etc. out there. I agree that a good intro video would be great (but I'm not the person to make it... script it, maybe...)

Great job!

**Comment by leo-arch** [comment]
I guess it's time hasn't come yet. People is too used to ranger/mc like (TUI) file managers: CliFM is different, and this is, I think, what keep most people from embracing it. Marketing is another big reason.

However, as a FOSS dev, I don't care so much (which of course doesn't mean I don't care at all) about how many users or starts the project has, but rather how many bugs, issues, and faults it has. This thing is for me like a work of art, and even a child: I just want to see it grow, become better and stronger.

Thanks for your kind words!

Btw, if you're eager to script a demo video, that would be great. Real users tend to be less biased than devs, and in this case that's a good thing. Once scripted, we only need someone to actually create the vid (not me of course; I really suck at multimedia stuff). But that's a different story.
