### ISSUE TITLE
details in file display

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#161]
Please add the possibility to see
- exact file size in bytes (right aligned)
- exact file time with seconds

This affects at least the long file view. Probably also the `p` command.

**Comment by leo-arch** [comment]
Done. Take a look at the updated [File details section](https://github.com/leo-arch/clifm/wiki/Common-Operations#file-details).

Added: files counter field, timestamp seconds, and the ability to print sizes in bytes.

As to the `p` command, it already includes seconds in timestamps.

**Comment by muellerto** [comment]
Thanks a lot, that's really an improvement.

I for my taste would add a 'B' on the right to make clear what this number is and I would also right align it. OK, aligning would need knowledge about the biggest file size of all files in the list ...

**Comment by leo-arch** [comment]
You're welcome!

Adding a B to indicate that we have a size expressed in bytes, it's a possibility I'll consider. Though, being not the default, the user needs to explicitly enable this feature, in which case s/he already knows the size will be expressed in bytes. Besides, this means one column less to print file names, which could be an issue when it comes to little displays.

As to right aligning the size column, I'm not sure about it: the remaining left fields are left aligned to improve readability. But, since there's no further right field next to the size column, there's no need to align it, at least not from a functional perspective. Even more, I think that right aligning this field would make it harder to read (the eye needs to search for the beginning of the number, which varies according to its length; it's clearly easier for the eye when all sizes start at the same column). So, this implies extra computation, both for the user and the machine itself, while the benefit is not that clear.

**Comment by muellerto** [comment]
I think (independent from the OS) most file managers do right align file sizes (and other numbers, especially counters). See file sizes in `ranger`, `lf`, `nnn`, `ls -l`, also `df`. I really can't rember any tool where it is different. `lsd -l` has right aligned file size numbers but left aligned units (B, kB, MB), exemplary to read.

The reason for that is easy: _comparability_ - digits with the same rank come at the same position. This may get important when you have a lot of very similar looking numbers with transposed digits.

**Comment by leo-arch** [comment]
I'll take a look at it.

**Comment by leo-arch** [comment]
Yeap, you're right, number are always right padded: I had not paid any attention to this fact. Thanks for pointing it out.

File counters, inode numbers, and size (in bytes only, for the time being), are now right padded.

**Comment by muellerto** [comment]
Looks great! :)
