### ISSUE TITLE
typing .. or ... or ....

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#165]
clifm allows to go upwards typing `..`. You can also type more dots, each additional dot is then expanded into /.., this means when you type `...` it means ../.., `....` means ../../.. Because of that implicit expansion the resulting relative path is explained right of the cursor:

    <0> $ ....._ ../../../../                        _ = cursor

Good so far.

But where do I really get when I press [Enter]? The explanation shows a relative path but where is it? The path can even be wrong (none existent) but will be shown.

I suggest two things:
- show the absolute resulting path here, the directory where I really get into
- show when the path gets wrong, when the user type to many dots

**Comment by leo-arch** [comment]
This should be done now.

* Absolute path is suggested next to dots
* If you type too many dots, you'll be taken into the root dir anyway (mimicking the shell behavior)

**Comment by muellerto** [comment]
Great. A real improvement.

**Comment by muellerto** [comment]
There's still a simple thing: if you typed some dots and then use [Backspace] the suggestion disappears completely. Why??? The dots are still there and a valid input but you can't see anymore where they will go :(

**Comment by leo-arch** [comment]
Hi @muellerto. Yes, that's true, but it's just the way suggestions work ueberhaupt: they only go forward, not backwards. Even Fish, which leads developments in this field, works that way.

**Comment by muellerto** [comment]
Don't understand that. Making a correction is of course also going forward. People are not machines, people are sometimes wrong.

When I have `.....` and get a suggestion for that then `....` will also be a valid and executable input but I have then no clue where I will land, only because I used [Backspace].

When I entered the four dots (before the fifth one) I had a suggestion for them, when I remove the fifth dot I don't get one anymore, that's hard to understand.

**Comment by leo-arch** [comment]
Totally agreed. Note that I'm not saying suggestions are _better_ they way they work now, but just that they work that way as a matter of fact. Lots of computing are needed before displaying a single suggestion, and we need this to be done very quickly (currently, indeed, **clifm** needs a bit more than two thousand lines of code to display a single suggestion). In other words, it's not a matter of how a function _should_ work (in which case you're absolutely right), but rather of how to implement it without turning the whole thing slow, and even unstable. 

In fact, the first implementations of _Gemini_, **clifm**'s suggestions system, included backward suggestions (and by backwards I mean suggesting even when you delete text), but I finally removed it due to performance and implementation details (which does not mean at all that in cannot be reimplemented, with a better algorithm, in the future).

**Comment by leo-arch** [comment]
Ok. I just reenabled backward suggestions. Since 1.8 we have massively improved suggestions performance, so this might turn out to work fine. However, I cannot guarantee there won't be any downsides. Please give it a try, and not only in the case of the fastback function: all suggestions support now "going backwards".

Compile as follows:

```sh
make CPPFLAGS=-DBACKWARD_SUGGEST install
```
This just unlocks the code to make backward suggestions work.

**Comment by muellerto** [comment]
Yes, in case of dots it seems to do the job as desired. Now I'm not sure where else this has consequences. Bad, I can't check this right now in detail because I'll not be at home for a week from now on. But since this is still hidden behind a define nobody else will get hurt by any unexpected malfunction. But thanks a lot!

**Comment by leo-arch** [comment]
Backward suggestions are now included with the regular build. To disable it, run **make**(1) as follows:

```sh
make CPPFLAGS=-DNO_BACKWARD_SUGGEST install
```
