### ISSUE TITLE
clifm directories

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#170]
**Describe the bug**
Something is not good finding the right clifm directories, the directories where clifm looks for its own files.

On Linux the application will normally be installed in `/usr/bin` or `/usr/local/bin`. Additional files get into `/usr/share` or `/usr/local/share`.

On Linux a problem occurs when the installation path should be different (yes, unusual), say a local directory under a user's home. Some people may also find `/opt` a good place. clifm will then not run properly because it's not able to locate some of its additional files. For some reason it looks still into `/usr/share` or `/usr/local/share` (not sure) but it couldn't find something there.

On Windows it gets an additional aspect because the paths are generally different and the user has another home directory. On Windows Cygwin or MinGW define their own implicit `/` which is then indeed something completely different, say `C:\msys64\` or so. There they have then a `/usr` and a `/usr/local`. clifm puts the user's configuration files into `/home/<username>/.config/clifm` but I'm not sure where this path comes from. No other application uses this `/home/<username>`.

A problem occurs on Windows when the user has a HOME environment variable different from that `/home/<username>`. I have this for reasons related to other applications. The problem is then that clifm searches for the user's `.config/clifm` directory sometimes under HOME (!) and sometimes under `/home/<username>`. To have a workaround I made a symbolic link into the directory named by my HOME environment variable having the same name `.config` pointing to `/home/<username>/.config`, so I have the same files on both places.

**Expected behavior**
- All the global files installed under `share` (I mean these *.clifm files, colors, shell scripts, plugins) should be accessed by the clifm binary using a relative approach always starting from the location of the binary itself. The location of the binary should be the only known constant. So the concrete installation path doesn't matter at all and even multiple installations will work.
- The user dependent files under `.config/clifm` should without an exception first be created and later be accessed in the directory named by the HOME environment variable. Note: on Windows this is probably a native path like `C:\Users\<username>\Documents\`. If the user doesn't have a HOME variable which will be the default case on Windows he should be urged to define one. Do not ask the OS or any library function for the user's home directory and don't assume a path like `/home/<username>`.

**Desktop**
- OS: Arch Linux, Windows 11
- Terminal: urxvt, Windows cmd.exe
- CliFM version: 1.8.4-beta (was also already the case in 1.8.3)
- Installation source: git

**Comment by leo-arch** [comment]
Hi @muellerto.

#### 1. Unix install dir

How did you set exactly an alternative install dir? The [documented/supported](https://github.com/leo-arch/clifm/wiki/Introduction#custom-installation-directory) way to do this is using **make**(1) and the `PREFIX` variable.   

This is how install directories are defined in the `Makefile`:

```sh
PREFIX ?= /usr/local
DATADIR ?= $(PREFIX)/share
MANDIR ?= $(PREFIX)/man
LOCALEDIR ?= $(DATADIR)/locale
DESKTOPPREFIX ?= $(DATADIR)/applications
DESKTOPICONPREFIX ?= $(DATADIR)/icons/hicolor
PROG_DATADIR ?= $(DATADIR)/$(BIN)
```
So. to define an alternative install dir, say `/opt`, you just need to set `PREFIX` as follows:

```sh
make PREFIX=/opt install
```
This should be smooth and painless.

Bear in mind that, in this case, and provided `/opt/bin` is not in your **PATH**, you need to enter the absolute path to clifm's binary for it to be executed:

```sh
$ /opt/bin/clifm
```

**NOTE**: If you just compile (via `gcc/clang`) and then move the resulting binary to somewhere else, then _clifm_ does not know what the _system_ install dir is (for it is only defined when compiled via **make**(1), as described above): a few common hardcoded paths will be tried as a fallback resource: `/usr/bin` and `/usr/local/bin` (I guess this is what you pointed out). Now, if the install dir isn't found, either `/usr/share/clifm` or `/usr/local/share/clifm`, then plugins, color schemes, manpage and extra files won't be accessible (these are copied from the install dir into the home dir if found). Only config files are created anew in the home dir (if not already there) by the binary itself.

#### 2. Window's home dir

Let me take a look at it.

**Comment by leo-arch** [comment]
Plugins were not working when using a non-standard install dir. Made a few changes to fix this: they should be working now.

Added also a `BINDIR` variable to the `Makefile` to allow setting a custom directory for the binary file. Example:

```sh
make PREFIX=/opt BINDIR=/usr/local/bin install
```
Everything will be installed in `/opt`, except the binary, which will be installed in `/usr/local/bin` (to avoid conflicts with **PATH**).

**Comment by muellerto** [comment]
I know the mechanism with the PREFIX variable and use it. But it didn't help in every aspect.

I will see what you did but can't do this before Monday.

But PREFIX or the other PREFIX dependent variables of the build system (make) should not affect the result of the compilation. The compiler should not get told where the final binary is to be installed and then compile a location dependent binary. The binary knows always where it is because it gets the path where it comes from in `argv[0]`. At least this is a hint (it can still be only a symbolic or hard link to the original place). So you can even move the binary somewhere else and it still knows where it comes from. This is also the case on Windows.

When you have installations in `/opt` you have normally application directories there and in each a specific hierarchy containing all the directories normally located in `/usr` or `/usr/local`:

```
/opt
    /app1
        /bin
        /etc
    /app2
        /bin
        /lib
        /man
        /share
            /app2           <- yes, again, because this is what you normally would see under /usr/share
    /app3
        /share
            /app3
                /node_modules
                (+ just a bunch of node.js scripts)
```

That's why I said the binary should access all other needed files always using relative paths based on its own physical location. When it is in `/opt/app2/bin` then it's immediately clear where the other files are. And the same mechanism would also just work under `/usr` or `/usr/local` or `c:\Program Files\app2`. I can just copy all the stuff there and it works. - A binary which is in `/usr/bin` has much more problems to access files in `/opt` or somewhere else. It must then have built-in previous knowledge or get runtime knowledge from a parameter or configuration file. And this gets immediately wrong when something is moved or renamed.

PATH doesn't matter. The OS finds executables in `/opt` either because you make then symbolic links into `/usr/bin` (or any other directory which is in PATH) or because you start the binary using a shell script.

**Comment by leo-arch** [comment]
I've already experimented with this approach in the past, but just found it to be unreliable. This was a few years ago, but let me recollect a few of the shortcomings I've found:

1. There's no secure/portable way to find the absolute path to the current executable file.
**a**. `argv[0]` is most of the time just the path's basename (because this is what we usually type in to run the program). If you run the program entering the executable's file name, say `clifm`, this is the only thing you get from `argv[0]`.
**b**. **realpath**(3) is of no help here, and as far as I know, there's no library able to guarantee the actual path to the running binary.
**c**. `/proc/self/exe`, and indeed the whole `/proc` thing, is Linux specific (or at least it is not guaranteed to be there on non-linux systems, i.e. it isn't POSIX.
**d**. Scanning **PATH** is not reliable either: you might be running a local copy of the program, while the **PATH** scan will probably find a copy under `/usr/bin`, which is not what we want. Scanning the current working directory is not enough either: you might be invoking the executable from any path in the file system.
2. Even if you do find the correct path, you still need to assume a specific directory tree as a base to reconstruct the remaining paths you need (config files), and once again, you're guessing: the executable's path could be _whatever_, and moving from whatever to your actual config files is far from a secure procedure. Not to mention that the running binary might perfectly be a hardlink far away from the original binary (and thereby from the config files you're looking for).

True, the current approach isn't bullet-proof either, as you can see, but _provided you install using the Makefile_, you should be fine. At least you can be reasonably sure about where your config files are: system-wide, they should be wherever the Makefile itself installed them (and we can know this at compilation time), and locally, we only need to check `~/.config/clifm`, which is where _clifm_ itself, I mean, the binary, creates local config files.

**Comment by leo-arch** [comment]
As to the home directory, up to 1.8.4, it was retrieved solely from the password database (via **getpwuid**(3)). Since 1.8.5, **HOME** is checked first, and, in case of error, we fallback to the password database. This should fix the issues you pointed out about the home dir. Please let me know if it works for you.

**Comment by muellerto** [comment]
> I've already experimented with this approach in the past, but just found it to be unreliable. This was a few years ago, but let me recollect a few of the shortcomings I've found:

Yeah, I should remember that myself, on Linux it's sometimes not reliable. On Windows it's always, you get always an absolute path to the executed binary. But also on Linux there are rules:
- when argv[0] is an absolute path it's clear
- when argv[0] is a relative path it must be based on the current working directory
- when argv[0] doesn't contain a path it must be a file in of one of the PATH-directories

> and locally, we only need to check ~/.config/clifm, which is where clifm itself, I mean, the binary, creates local config files.

On Linux it's clear. On Windows this is a problem, as I found out. clifm creates the user specific files under `/home/<username>/.config/clifm`, but requests them under the directory named by the HOME variable which may indeed be different.

**Comment by muellerto** [comment]
> As to the home directory, up to 1.8.4, it was retrieved solely from the password database (via **getpwuid**(3)). Since 1.8.5, **HOME** is checked first, and, in case of error, we fallback to the password database. This should fix the issues you pointed out about the home dir. Please let me know if it works for you.

I check this tomorrow when I have my Windows machine back.

**Comment by leo-arch** [comment]
> on Linux there are rules

These rules do not conflict with the current approach. Currently, this is what _clifm_ does to get the install dir:

1. Check whether **CLIFM_DATADIR** is defined, which is the case when installed via the `Makefile`.
2. If not defined, check some default paths: `/usr/share`, `/usr/local/share`, and a few more.

We could just add a third step, in case both 1 and 2 failed: try to guess based on the binary's path.

EDIT: Maybe we can even add a new command line switch to let the user define the install dir, say:

```sh
clifm --data-dir=/opt/share
```
This would take precedence over the three checks above.

**Comment by leo-arch** [comment]
### New data dir implementation

This is how _clifm_ attempts now to get its data directory (in this exact order):

1. Grab it from `--data-dir`, if specified (see below).
2. Check the CLIFM_DATADIR macro, only there if defined via the `Makefile`.
3. Try some standard directories, mostly `/usr/share` and `/usr/local/share`.
4. Try to guess it using whatever value is provided by `argv[0]`.

What the new algorithm looks for? Basically, we look for the main configuration file, i.e. `clifmrc`. For each of the steps above, the following procedures are performed:

1. Remove ending `/bin` from the testing directory
2. Append `/share/clifm` or just `clifm` and search for the config file: `DIR/share/clifm/clifmrc` or `DIR/clifm/clifmrc`.
3. Make sure the file exists (under the specified directory) and is a regular file.

Provided all these steps succeed, we have our data directory.

Note that this procedure assumes that, if `clifmrc` is found, the whole directory tree (as created by a default installation under `/usr/local/share`) will be there too. It makes no sense to check for each single file at startup, since data files are dynamic and should not be made part of the source code, so that this is the most we can do. 

This is the expected directory tree:

```sh
/usr/share/
└──clifm
      ├── actions.clifm
      ├── clifmrc
      ├── colors
      │   └...
      ├── functions
      │   └ ...
      ├── keybindings.clifm
      ├── mimelist.clifm
      ├── nets.clifm
      ├── plugins
      │   └...
      ├── preview.clifm
      ├── prompts.clifm
      ├── readline.clifm
      └── tools
          └...
```

### A simple test

1. Copy the executable (`clifm`, latest git version, of course) and the entire `share/clifm` directory into a custom dir, say `~/mydir`. It should look like this:

```
~/mydir/
├─ clifm (binary)
└─ share/
    └─ clifm/
        └...
```

2. Remove the original `/usr/local/share/clifm` directory to make sure data files are actually loaded from `~/mydir/share/clifm`. (because of the precedence order described above, if `/usr/local/share/clifm` is found, it will be used instead of `~/mydir/share/clifm`).
3. Now you can run this binary and the custom data dir should be autodetected based on the binary location (step 4 above):

```
$ ~/mydir/clifm
```

To make sure it works, just try to list available color schemes (they should be loaded from your custom data dir):

```
cs <TAB>
```

**Note**: Running a plugin should also do the trick. Just note that some plugins might not work. `gg`, for example, looks for the `clifm` binary somewhere in your **PATH**, and in this scenario, the only existent binary is located in `~/mydir`. Same thing with `ih`: it will try to load the manpage via **man**(1), but it won't be able to find it.

#### The `--data-dir` switch

You can also run the binary from wherever else and point to your custom data dir via the `--data-dir` command line switch. For example:

```
$ /path/to/clifm --data-dir=~/mydir
# ~/mydir/share works as well
```

**Comment by muellerto** [comment]
With the latest changes (1.8.5-beta) the situation on Windows is much better. The directory `/home/<username>` is now not affected at all anymore, good so. clifm creates the user specific files now in the directory the HOME environment variable names and it finds them also there. This looks good.

To have this `--data-dir` parameter is perhaps a good idea. This should allow the user to have clifm including the files anywhere and to use a shell script for starting it. We know this will not be the standard case but it allows the user to have a complete private place for tests or whatever, when he doesn't want to modify his running OS.

Close?

**Comment by leo-arch** [comment]
Closing then. Feel free to reopen this issue if some related problem comes up.
