### ISSUE TITLE
Couldn't abort a move operation

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#182]
**Describe the bug**
I couldn't abort a move operation after misspelling.

**To Reproduce**
I had a file in the selection, then I changed the directory. Now I tried to move it here using the `m` command but I misspelled `sel`, I wrote `sek`:
```
<0> $ m sek
Enter new name ('Ctrl-d' to quit)
>
```

This resulted in the question for a new file name. Perhaps I could write `sel` now. But I chose to abort this action using `Ctrl-D`. But this key combination aborts clifm, not the action. Is this intended? Other keys (`Ctrl-C`, `ESC`) do not work. So the user must provide a file name which is then to be moved or abort clifm.

**Expected behavior**
I thought it would be good just to terminate the operation, not clifm.

**Desktop**
- OS: Windows 11
- Terminal: ConEmu, DOS prompt
- CliFM version: fresh 1.9.2
- Installation source: Git

**Comment by leo-arch** [comment]
Hi @muellerto. We have two issues in one here:

1. You shouldn't have been prompted to enter a new file name for a file name (`sek`) that doesn't exist.
2. The issue you actually described.

I have already reproduced and fixed the first one (though haven't uploaded the fix yet). As to the second one, not there on Linux. I'll try on Window (maybe there's some keyboard layout issue there). Ill let you know.

**Comment by leo-arch** [comment]
Btw, have you noticed the new command description suggestions? What do you think about it?

**Comment by leo-arch** [comment]
Ok. The fix for the first issue is uploaded.

**Comment by muellerto** [comment]
That's OK so. I'll close it.

**Comment by muellerto** [comment]
> Btw, have you noticed the new command description suggestions? What do you think about it?

Yes, I saw this surprisingly. Nice! And a really good idea on a command line. Now I also know what the `tu` command does. Maybe this helps to make less wrong inputs because you see immediately that you really get what you wanted or something unexpected, especially if the amount of commands (and user defined abbreviations) is still getting bigger. 

I'm not sure if it helps to learn more commands, this would require that the user sees also other possible commands when he types a letter. IntelliSense provides this by popping up a local context menu with a number of lines available for more information:

http://cuneyt-aliustaoglu.s3.amazonaws.com/blog-en/2017-10-15-Vscode-Arduino/Intellisense.png

But a popup menu would be not easy to implement in an ASCII environment. Probably such a thing would here also be more a deviation than a help.

**Comment by leo-arch** [comment]
Thanks! I'm still looking forward for ways to improve this feature. For example:

1. The suggestion color is currently not customizable: it's fixed to dimmed white (gray), which might not work on some terminals. For instance, I noticed that it is not honored on the ConEmu terminal, and I'm sure it's not the only one. This could be easily fixed by just adding a new color code.
2. Only predefined internal commands are supported. Plugins are not included: they are external commands, for which we would need a new mechanism to load descriptions from the outside. But doing this would slow down the suggestions process, which needs to be kept as fast as possible.
3. The command syntax could also be provided. This can be easily achieved, but it might result in too long descriptions (which are supposed to be quite brief to keep them quick and useful).
4. Providing a menu for other possible commands as you type will surely be useful, but, as you said, implementing this feature on a command line environment, while possible (fzf might be used for example), is way beyond the native capabilities of such environment.

Just thinking aloud. Anyway, thanks for your suggestions!

**Comment by leo-arch** [comment]
I forgot yo add that you can disable this new feature by setting the `SuggestCmdDesc` option to `false` in the config file.

**Comment by leo-arch** [comment]
Color for command description suggestion can be customized now via the `sd` color code in the color scheme file.

**Comment by leo-arch** [comment]
Not exactly what you suggested, but quite close: type `cmd<TAB>` to get a list of available commands together with a brief description.

**Comment by muellerto** [comment]
Cool. Add your new short descriptions there for your internal commands. That would be great. For instance when you type `t<TAB>` you get all these trash commands listed (hey, trash commands!). The list is long but you don't see what is what, you can't even distinguish them from the externals. Short descriptions would solve this.

Note: there could also be doubles, an internal and an external in that list. (There could also be more, several externals with the same name.)

BTW: yesterday I typed `.....` on a bash command line and wondered about the missing prediction right from the cursor and the resulting error message. What error??? - These dots together with the prediction are one of the coolest things in clifm, I use them a lot.

**Comment by leo-arch** [comment]
For the time being, `cmd<TAB>` lists only short internal commands plus a brief description. It is intended to be just some kind of hint about available commands. Then you can always use `--help` to get full information about each command.

As to the fastback function, yeah, it's pretty handy indeed, and this partly because of your feedback. Kudos for that!

EDIT:
btw, `cmd` is literally a command.
