### ISSUE TITLE
take `sel` as default argument

### ISSUE THREAD

**Issue by muellerto** [leo-arch/CliFM#185]
**Is your feature request related to a problem? Please describe.**
Operations needing an argument could be typed easier when `sel` would be a default.

**Describe the solution you'd like**
The `c`, `m` and `r` commands for example are often called as `c sel`, `m sel`, `r sel`. I do so. But many times I had (especially in my role as an ordinary sloth) already the idea why can't I just type `c` or `m` or `r` instead. Should be clear that I mean the selection I made a second before.

Not sure, if this would always be possible. But at least when no other argument is given and a selection is currently known.

**Alternative**
With regard to the `ds` command which has the selection explicitly in its name there could also be special implementations of `c`, `m` and `r` called `cs`, `ms` and `rs`. OK, I could make aliases for them.

**Comment by muellerto** [comment]
Damned, `cs` does already exist (know that ...). `C`, `M` and `R`!

**Comment by leo-arch** [comment]
Hi @muellerto. A few observations:

1. Assuming `sel` in case either `c`, `m`, or `r` commands have no further parameter and there are selected files, _might be_ implemented, but optionally. It is indeed a good idea, useful; but it might break the user interface, and that's never a good idea. I'll think about it.
2. You can actually write an alias named `cs`, despite this is an internal command. Aliases take precedence. in any case, besides that `cs` is not an important command (it just changes the color scheme), you can always skip the alias using a backslash: `\cs`.
3. Yes, you can use any of those aliases. However, while testing this a bug came out: if the aliased command fails, for example, because there are no selected files, the original command will be executed, and it shouldn't. This is the case with this alias: `alias cs="c sel"`: provided there are no selected files, the `cs` command (not the alias), will be executed. Working on it.

**Comment by leo-arch** [comment]
The aliases issue mentioned above (point 3) should be solved now. So, an alias should be enough by now, However, bear in mind that parameters passed to the alias in the command line will be appended to the aliased command. For example, if your alias is:

```sh
alias C="c sel"
```
and then you enter

```
C file.txt
```

this will be understood as `c sel file.txt`. Be very careful when using this: the current directory is appended only provided `sel` is the _last_ word, which is not the case in this example. You might end up overwriting `file.txt`.

**Comment by leo-arch** [comment]
One more thing. You can certainly use `cs` as an alias name, but since this is an internal command, it has its own set of rules: ELN's won't be expanded (because `cs` takes no ELN, but just color scheme names) as parameter; TAB completion and suggestions will take this name as the internal command name (not as an alias), and a few more things tailored for this specific command. So, you can, but it has its drawbacks. On the other side, any name which is not an internal command name should be fine.

**Comment by muellerto** [comment]
Used several upper letters now. (Also good to keep them in mind.) And for me it's clear that they are normally not called with arguments. OK, when you still do it the additional arguments should just be added to the `sel` in the alias, that's intuitive. Works good this way.
