### ISSUE TITLE
Fastfetch bug

### ISSUE THREAD

**Issue by theRoboxx** [leo-arch/CliFM#289]
**Describe the bug**
`fastfetch` crashes when listing the **Shell** parameter

**To Reproduce**
1. Run `fastfetch` in foot-client
2. Displays information until **Shell** parameter
3. **Shell** parameter doesn't get displayed and freezes

**Expected behavior**
The `fastfetch` command should list every Laptop information

**Screenshots**
Fish vs. Clifm
![fastfetch](https://github.com/leo-arch/clifm/assets/63428105/c4ac371d-de61-46bc-bd01-c5f72e7dcf33)

**Desktop (please complete the following information):**
 - OS: Nixos Unstable 24.05
 - Terminal: Foot
 - CliFM version: clifm 1.18 (Mar 23, 2024)
- Installation source: nix unstable branch

**Comment by leo-arch** [comment]
Hi @theRoboxx. Reproduced with version 18.0. However, the issue is not there in the latest git version. Please give it a try.

**Comment by muellerto** [comment]
clifm 1.18.4 (Apr 22, 2024)
![1](https://github.com/leo-arch/clifm/assets/5188366/78d54dcd-40d6-4edb-8778-0d6cc77f2e3e)

**Comment by muellerto** [comment]
OK, on my Arch it says just "clifm":
![1](https://github.com/leo-arch/clifm/assets/5188366/ead81121-41a4-4e5a-bd4b-290241d212b5)

**Comment by leo-arch** [comment]
Thanks for your confirmation @muellerto.

As to the `Shell` field showing `clifm` (on Linux), I'm not sure why (but this is most likely related to `fastfetch` rather than to `clifm` itself). It might be because `fastfetch` is getting the running shell by consulting the parent PID, but I'm not sure.

EDIT: Yeap, that's what it actually seems to be doing (i.e. checking `/proc/PID/stat`):

https://github.com/fastfetch-cli/fastfetch/blob/445dd94b53f0903f35989dca47eeaa6edeb53f86/src/detection/terminalshell/terminalshell_linux.c#L124

**Comment by CarterLi** [comment]
Happened to find this.

Fastfetch have resolved similar issues by adding them to ignore list. I can do the same for clifm if needed.

**Comment by leo-arch** [comment]
That would be great @CarterLi. Thanks!

**Comment by CarterLi** [comment]
Just tried clifm. Seems that clifm spawn $SHELL process to run shell commands, so that the process tree is: `terminal > shell > clifm > shell > fastfetch`

So the problematic module should be `Terminal` instead of `Shell`

<img width="462" alt="image" src="https://github.com/leo-arch/clifm/assets/6134068/8a98bba8-4f39-44d0-a6e5-e8701321c374">

Really curious why it worked differently in @muellerto's screenshot.

Anyway, I will make fastfetch ignore clifm in both Shell & Terminal module

**Comment by leo-arch** [comment]
> the process tree is: terminal > shell > clifm > shell > fastfetch

This is true.

As to the Terminal field, I'm getting the right value, no matter what terminal I use.

Btw, I normally run **clifm** under valgrind, in which case `fastfetch` takes valgrind as my shell. I guess you should add valgrind to the shell ignore list too.

**Comment by CarterLi** [comment]
okey

**Comment by leo-arch** [comment]
Hey @theRoboxx, can we mark this issue as solved?
