### ISSUE TITLE
`columns on`: file listing by lines instead of columns

### ISSUE THREAD

**Issue by listentolist** [leo-arch/clifm#50]
The command `columns on` (the default) is a bit confusing as the entries are listed by lines rather than columns:

```
1 2 3
4 5 6
7 8 9
```
instead of
```
1 4 7
2 5 8
3 6 9
```

(just like the difference between `ls -x` (lines) and `ls -C` (columns))

I suggest to follow the `ls` command and list the files in columns by default. The `columns` command should be changed to something like `listing-style [columns, lines, 1]`.

**Comment by leo-arch** [comment]
Hi @listentolist. Maybe it's a bit confusing, true. But by `columns` I understand listing files in columns rather than sequentially, one after the other (one per row). 

As to the listing style, yes, I do not follow `ls` style. But this is not arbitrary nor a caprice. When I began this project, the idea was to list files using the `ls` style: but it turned out to be not as easy to implement. After many tries (and failures), the current listing style resulted better (at least for me) from the development viewpoint.

However, and though this is not a priority at all, I'll definitely add this to my TODO list. As soon as I have time (currently struggling with the syntax highlighting system), I'll take a look at it. Maybe today (I'm better at coding than a few years ago) I could finally implement the `ls` style, at least optionally.

Thanks for your suggestion.
