### ISSUE TITLE
fzfnav-like preview in fzfsel

### ISSUE THREAD

**Issue by ohle** [leo-arch/clifm#51]
Would it be possible to get fzfnav-like previews in fzfsel? Or alternatively a selection feature in fzfnav?

**Comment by leo-arch** [comment]
I'll take a look at it. I guess it would be simpler to implement files selection in fzfnav than previews in fzfsel. Let me see what I can do.

**Comment by leo-arch** [comment]
Well, I added file selection capability to `fzfnav`. There are a few things to solve/improve, but it basically works. Try it and let me know.

I bound <kbd>TAB</kbd> to mark files for selection and <kbd>Ctrl-s</kbd> to confirm the selection (send files to CliFM's Selbox). The current selection is removed when the current directory is changed, so that you need to press <kbd>Ctrl-s</kbd> to save currently selected files and then move to another directory, where you can select more files.

**Comment by ohle** [comment]
Looks good, thanks!
