### ISSUE TITLE
Additional steps for Konsole shortcuts

### ISSUE THREAD

**Issue by JohannesGaessler** [leo-arch/clifm#57]
I'm using Konsole and I made the changes described in the man page regarding shift+left and shift+right.
This was not enough however.
On Konsole those shortcuts by default switch to the tab on the left/right of the current tab and need to be unbound first via Settings -> Configure Keyboard Shortcuts...

**Comment by leo-arch** [comment]
Thanks for pointing this out @JohannesGaessler! Keybindings are quite tricky to implement, precisely because of this kind of things (keybinds might be already taken by the terminal/console/OS). Let me see if I can get some way around it. In the worst scenario, adding the additional step to the manpage would be better than nothing.

**Comment by leo-arch** [comment]
I finally just added the extra step to the docs (both wiki and manpge). Thanks again @JohannesGaessler.
