### ISSUE TITLE
bulk rename not working

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#81]
when I try something like
```
br 1-5
```
it gives me
```
bulk: Nothing to do
```

**Comment by leo-arch** [comment]
What kind of files are you trying to rename? Does the "Nothing to do" message pop up immediately after issuing the `br` command?

`br` creates a temporary regular file an attempts to open it via the `mime` function, or, if set, via a custom opener. Are you using a custom opener? Perhaps `br` is unable to find an application to open the temporary file.

**Comment by Docbroke** [comment]
Kind of files doesn't matter. 
"nothing to do" appears immediately followed by empty vis window opening in sakura ( text files are opened with "sakura -e vis %f &" as per lira config)

**Comment by Docbroke** [comment]
Indeed problem is with "sakura -e vis %f &", Let me try something else, and report back

**Comment by leo-arch** [comment]
Try removing the final ampersand from the command. I think the problem is that the temporary file is opened in the background, so that `br` has no way to know if some file name was modified, because the process returns immediately after opening the file.

However, `br` should never open the temporary file in the background. I'll fix it.

**Comment by Docbroke** [comment]
"&" is not playing nice with `br`

**Comment by leo-arch** [comment]
Fixed.

`br` won't open the temp file in the background, no matter what the mimelist file says.
