### ISSUE TITLE
formating issue with indic languages

### ISSUE THREAD

**Issue by Docbroke** [leo-arch/CliFM#91]
![image](https://user-images.githubusercontent.com/16881701/146636168-8fbbf05c-30ea-4de6-b0e5-40dadd413665.jpg)

**Comment by leo-arch** [comment]
You have spotted one of the top 5 issues: full Unicode support.

In this case, the thing is `MaxNameLen`: trimming Unicode file names is not as easy as it sounds. Several key functions need to be refactored to work with wide chars instead of simple bytes (ASCII), just as I did with long view.

Refactoring these functions won't be easy, but is definitely a must.

**Comment by leo-arch** [comment]
I have a first working version. Just a few more tests and tomorrow I'll push it to master.

**Comment by leo-arch** [comment]
Done. Already in master.

**Comment by Docbroke** [comment]
thanks
